//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace HB.UpgradeService.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class DBContainer : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“DBContainer”部分中的连接字符串初始化新 DBContainer 对象。
        /// </summary>
        public DBContainer() : base("name=DBContainer", "DBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DBContainer 对象。
        /// </summary>
        public DBContainer(string connectionString) : base(connectionString, "DBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 DBContainer 对象。
        /// </summary>
        public DBContainer(EntityConnection connection) : base(connection, "DBContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<RuleInfo> RuleInfo
        {
            get
            {
                if ((_RuleInfo == null))
                {
                    _RuleInfo = base.CreateObjectSet<RuleInfo>("RuleInfo");
                }
                return _RuleInfo;
            }
        }
        private ObjectSet<RuleInfo> _RuleInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<TerminalInfo> TerminalInfo
        {
            get
            {
                if ((_TerminalInfo == null))
                {
                    _TerminalInfo = base.CreateObjectSet<TerminalInfo>("TerminalInfo");
                }
                return _TerminalInfo;
            }
        }
        private ObjectSet<TerminalInfo> _TerminalInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<UserInfo> UserInfo
        {
            get
            {
                if ((_UserInfo == null))
                {
                    _UserInfo = base.CreateObjectSet<UserInfo>("UserInfo");
                }
                return _UserInfo;
            }
        }
        private ObjectSet<UserInfo> _UserInfo;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<VersionInfo> VersionInfo
        {
            get
            {
                if ((_VersionInfo == null))
                {
                    _VersionInfo = base.CreateObjectSet<VersionInfo>("VersionInfo");
                }
                return _VersionInfo;
            }
        }
        private ObjectSet<VersionInfo> _VersionInfo;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 RuleInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToRuleInfo(RuleInfo ruleInfo)
        {
            base.AddObject("RuleInfo", ruleInfo);
        }
    
        /// <summary>
        /// 用于向 TerminalInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToTerminalInfo(TerminalInfo terminalInfo)
        {
            base.AddObject("TerminalInfo", terminalInfo);
        }
    
        /// <summary>
        /// 用于向 UserInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToUserInfo(UserInfo userInfo)
        {
            base.AddObject("UserInfo", userInfo);
        }
    
        /// <summary>
        /// 用于向 VersionInfo EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToVersionInfo(VersionInfo versionInfo)
        {
            base.AddObject("VersionInfo", versionInfo);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB", Name="RuleInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RuleInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 RuleInfo 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="ruleName">RuleName 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        public static RuleInfo CreateRuleInfo(global::System.Guid id, global::System.String ruleName, global::System.DateTime createTime)
        {
            RuleInfo ruleInfo = new RuleInfo();
            ruleInfo.Id = id;
            ruleInfo.RuleName = ruleName;
            ruleInfo.CreateTime = createTime;
            return ruleInfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RuleName
        {
            get
            {
                return _RuleName;
            }
            set
            {
                OnRuleNameChanging(value);
                ReportPropertyChanging("RuleName");
                _RuleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RuleName");
                OnRuleNameChanged();
            }
        }
        private global::System.String _RuleName;
        partial void OnRuleNameChanging(global::System.String value);
        partial void OnRuleNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AppVersion
        {
            get
            {
                return _AppVersion;
            }
            set
            {
                OnAppVersionChanging(value);
                ReportPropertyChanging("AppVersion");
                _AppVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AppVersion");
                OnAppVersionChanged();
            }
        }
        private global::System.String _AppVersion;
        partial void OnAppVersionChanging(global::System.String value);
        partial void OnAppVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImgVersion
        {
            get
            {
                return _ImgVersion;
            }
            set
            {
                OnImgVersionChanging(value);
                ReportPropertyChanging("ImgVersion");
                _ImgVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImgVersion");
                OnImgVersionChanged();
            }
        }
        private global::System.String _ImgVersion;
        partial void OnImgVersionChanging(global::System.String value);
        partial void OnImgVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BootVersion
        {
            get
            {
                return _BootVersion;
            }
            set
            {
                OnBootVersionChanging(value);
                ReportPropertyChanging("BootVersion");
                _BootVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BootVersion");
                OnBootVersionChanged();
            }
        }
        private global::System.String _BootVersion;
        partial void OnBootVersionChanging(global::System.String value);
        partial void OnBootVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BDVersion
        {
            get
            {
                return _BDVersion;
            }
            set
            {
                OnBDVersionChanging(value);
                ReportPropertyChanging("BDVersion");
                _BDVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BDVersion");
                OnBDVersionChanged();
            }
        }
        private global::System.String _BDVersion;
        partial void OnBDVersionChanging(global::System.String value);
        partial void OnBDVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavVersion
        {
            get
            {
                return _NavVersion;
            }
            set
            {
                OnNavVersionChanging(value);
                ReportPropertyChanging("NavVersion");
                _NavVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavVersion");
                OnNavVersionChanged();
            }
        }
        private global::System.String _NavVersion;
        partial void OnNavVersionChanging(global::System.String value);
        partial void OnNavVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavCardVersio
        {
            get
            {
                return _NavCardVersio;
            }
            set
            {
                OnNavCardVersioChanging(value);
                ReportPropertyChanging("NavCardVersio");
                _NavCardVersio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavCardVersio");
                OnNavCardVersioChanged();
            }
        }
        private global::System.String _NavCardVersio;
        partial void OnNavCardVersioChanging(global::System.String value);
        partial void OnNavCardVersioChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardVersion
        {
            get
            {
                return _CardVersion;
            }
            set
            {
                OnCardVersionChanging(value);
                ReportPropertyChanging("CardVersion");
                _CardVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardVersion");
                OnCardVersionChanged();
            }
        }
        private global::System.String _CardVersion;
        partial void OnCardVersionChanging(global::System.String value);
        partial void OnCardVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB", Name="TerminalInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TerminalInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 TerminalInfo 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="sN">SN 属性的初始值。</param>
        /// <param name="terminalNo">TerminalNo 属性的初始值。</param>
        /// <param name="sIM">SIM 属性的初始值。</param>
        /// <param name="plateNO">PlateNO 属性的初始值。</param>
        /// <param name="vehicleType">VehicleType 属性的初始值。</param>
        /// <param name="customerCode">CustomerCode 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        public static TerminalInfo CreateTerminalInfo(global::System.Guid id, global::System.String sN, global::System.String terminalNo, global::System.String sIM, global::System.String plateNO, global::System.String vehicleType, global::System.String customerCode, global::System.DateTime createTime)
        {
            TerminalInfo terminalInfo = new TerminalInfo();
            terminalInfo.Id = id;
            terminalInfo.SN = sN;
            terminalInfo.TerminalNo = terminalNo;
            terminalInfo.SIM = sIM;
            terminalInfo.PlateNO = plateNO;
            terminalInfo.VehicleType = vehicleType;
            terminalInfo.CustomerCode = customerCode;
            terminalInfo.CreateTime = createTime;
            return terminalInfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SN
        {
            get
            {
                return _SN;
            }
            set
            {
                OnSNChanging(value);
                ReportPropertyChanging("SN");
                _SN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SN");
                OnSNChanged();
            }
        }
        private global::System.String _SN;
        partial void OnSNChanging(global::System.String value);
        partial void OnSNChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TerminalNo
        {
            get
            {
                return _TerminalNo;
            }
            set
            {
                OnTerminalNoChanging(value);
                ReportPropertyChanging("TerminalNo");
                _TerminalNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TerminalNo");
                OnTerminalNoChanged();
            }
        }
        private global::System.String _TerminalNo;
        partial void OnTerminalNoChanging(global::System.String value);
        partial void OnTerminalNoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SIM
        {
            get
            {
                return _SIM;
            }
            set
            {
                OnSIMChanging(value);
                ReportPropertyChanging("SIM");
                _SIM = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SIM");
                OnSIMChanged();
            }
        }
        private global::System.String _SIM;
        partial void OnSIMChanging(global::System.String value);
        partial void OnSIMChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlateNO
        {
            get
            {
                return _PlateNO;
            }
            set
            {
                OnPlateNOChanging(value);
                ReportPropertyChanging("PlateNO");
                _PlateNO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PlateNO");
                OnPlateNOChanged();
            }
        }
        private global::System.String _PlateNO;
        partial void OnPlateNOChanging(global::System.String value);
        partial void OnPlateNOChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VehicleType
        {
            get
            {
                return _VehicleType;
            }
            set
            {
                OnVehicleTypeChanging(value);
                ReportPropertyChanging("VehicleType");
                _VehicleType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VehicleType");
                OnVehicleTypeChanged();
            }
        }
        private global::System.String _VehicleType;
        partial void OnVehicleTypeChanging(global::System.String value);
        partial void OnVehicleTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CustomerCode
        {
            get
            {
                return _CustomerCode;
            }
            set
            {
                OnCustomerCodeChanging(value);
                ReportPropertyChanging("CustomerCode");
                _CustomerCode = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CustomerCode");
                OnCustomerCodeChanged();
            }
        }
        private global::System.String _CustomerCode;
        partial void OnCustomerCodeChanging(global::System.String value);
        partial void OnCustomerCodeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AppVersion
        {
            get
            {
                return _AppVersion;
            }
            set
            {
                OnAppVersionChanging(value);
                ReportPropertyChanging("AppVersion");
                _AppVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AppVersion");
                OnAppVersionChanged();
            }
        }
        private global::System.String _AppVersion;
        partial void OnAppVersionChanging(global::System.String value);
        partial void OnAppVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ImgVersion
        {
            get
            {
                return _ImgVersion;
            }
            set
            {
                OnImgVersionChanging(value);
                ReportPropertyChanging("ImgVersion");
                _ImgVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ImgVersion");
                OnImgVersionChanged();
            }
        }
        private global::System.String _ImgVersion;
        partial void OnImgVersionChanging(global::System.String value);
        partial void OnImgVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BootVersion
        {
            get
            {
                return _BootVersion;
            }
            set
            {
                OnBootVersionChanging(value);
                ReportPropertyChanging("BootVersion");
                _BootVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BootVersion");
                OnBootVersionChanged();
            }
        }
        private global::System.String _BootVersion;
        partial void OnBootVersionChanging(global::System.String value);
        partial void OnBootVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BDVersion
        {
            get
            {
                return _BDVersion;
            }
            set
            {
                OnBDVersionChanging(value);
                ReportPropertyChanging("BDVersion");
                _BDVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BDVersion");
                OnBDVersionChanged();
            }
        }
        private global::System.String _BDVersion;
        partial void OnBDVersionChanging(global::System.String value);
        partial void OnBDVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavVersion
        {
            get
            {
                return _NavVersion;
            }
            set
            {
                OnNavVersionChanging(value);
                ReportPropertyChanging("NavVersion");
                _NavVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavVersion");
                OnNavVersionChanged();
            }
        }
        private global::System.String _NavVersion;
        partial void OnNavVersionChanging(global::System.String value);
        partial void OnNavVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NavCardVersion
        {
            get
            {
                return _NavCardVersion;
            }
            set
            {
                OnNavCardVersionChanging(value);
                ReportPropertyChanging("NavCardVersion");
                _NavCardVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NavCardVersion");
                OnNavCardVersionChanged();
            }
        }
        private global::System.String _NavCardVersion;
        partial void OnNavCardVersionChanging(global::System.String value);
        partial void OnNavCardVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CardVersion
        {
            get
            {
                return _CardVersion;
            }
            set
            {
                OnCardVersionChanging(value);
                ReportPropertyChanging("CardVersion");
                _CardVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CardVersion");
                OnCardVersionChanged();
            }
        }
        private global::System.String _CardVersion;
        partial void OnCardVersionChanging(global::System.String value);
        partial void OnCardVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewAppVersion
        {
            get
            {
                return _NewAppVersion;
            }
            set
            {
                OnNewAppVersionChanging(value);
                ReportPropertyChanging("NewAppVersion");
                _NewAppVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewAppVersion");
                OnNewAppVersionChanged();
            }
        }
        private global::System.String _NewAppVersion;
        partial void OnNewAppVersionChanging(global::System.String value);
        partial void OnNewAppVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewImgVersion
        {
            get
            {
                return _NewImgVersion;
            }
            set
            {
                OnNewImgVersionChanging(value);
                ReportPropertyChanging("NewImgVersion");
                _NewImgVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewImgVersion");
                OnNewImgVersionChanged();
            }
        }
        private global::System.String _NewImgVersion;
        partial void OnNewImgVersionChanging(global::System.String value);
        partial void OnNewImgVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewBootVersion
        {
            get
            {
                return _NewBootVersion;
            }
            set
            {
                OnNewBootVersionChanging(value);
                ReportPropertyChanging("NewBootVersion");
                _NewBootVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewBootVersion");
                OnNewBootVersionChanged();
            }
        }
        private global::System.String _NewBootVersion;
        partial void OnNewBootVersionChanging(global::System.String value);
        partial void OnNewBootVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewBDVersion
        {
            get
            {
                return _NewBDVersion;
            }
            set
            {
                OnNewBDVersionChanging(value);
                ReportPropertyChanging("NewBDVersion");
                _NewBDVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewBDVersion");
                OnNewBDVersionChanged();
            }
        }
        private global::System.String _NewBDVersion;
        partial void OnNewBDVersionChanging(global::System.String value);
        partial void OnNewBDVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewNavVersion
        {
            get
            {
                return _NewNavVersion;
            }
            set
            {
                OnNewNavVersionChanging(value);
                ReportPropertyChanging("NewNavVersion");
                _NewNavVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewNavVersion");
                OnNewNavVersionChanged();
            }
        }
        private global::System.String _NewNavVersion;
        partial void OnNewNavVersionChanging(global::System.String value);
        partial void OnNewNavVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewNavCardVersion
        {
            get
            {
                return _NewNavCardVersion;
            }
            set
            {
                OnNewNavCardVersionChanging(value);
                ReportPropertyChanging("NewNavCardVersion");
                _NewNavCardVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewNavCardVersion");
                OnNewNavCardVersionChanged();
            }
        }
        private global::System.String _NewNavCardVersion;
        partial void OnNewNavCardVersionChanging(global::System.String value);
        partial void OnNewNavCardVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NewCardVersion
        {
            get
            {
                return _NewCardVersion;
            }
            set
            {
                OnNewCardVersionChanging(value);
                ReportPropertyChanging("NewCardVersion");
                _NewCardVersion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NewCardVersion");
                OnNewCardVersionChanged();
            }
        }
        private global::System.String _NewCardVersion;
        partial void OnNewCardVersionChanging(global::System.String value);
        partial void OnNewCardVersionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Longitude;
        partial void OnLongitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private Nullable<global::System.Decimal> _Latitude;
        partial void OnLatitudeChanging(Nullable<global::System.Decimal> value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RuleInfoName
        {
            get
            {
                return _RuleInfoName;
            }
            set
            {
                OnRuleInfoNameChanging(value);
                ReportPropertyChanging("RuleInfoName");
                _RuleInfoName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RuleInfoName");
                OnRuleInfoNameChanged();
            }
        }
        private global::System.String _RuleInfoName;
        partial void OnRuleInfoNameChanging(global::System.String value);
        partial void OnRuleInfoNameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB", Name="UserInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 UserInfo 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="userName">UserName 属性的初始值。</param>
        /// <param name="password">Password 属性的初始值。</param>
        public static UserInfo CreateUserInfo(global::System.Guid id, global::System.String userName, global::System.String password)
        {
            UserInfo userInfo = new UserInfo();
            userInfo.Id = id;
            userInfo.UserName = userName;
            userInfo.Password = password;
            return userInfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB", Name="VersionInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VersionInfo : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 VersionInfo 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        /// <param name="versionName">VersionName 属性的初始值。</param>
        /// <param name="terminalFileType">TerminalFileType 属性的初始值。</param>
        /// <param name="createTime">CreateTime 属性的初始值。</param>
        public static VersionInfo CreateVersionInfo(global::System.Guid id, global::System.String versionName, global::System.String terminalFileType, global::System.DateTime createTime)
        {
            VersionInfo versionInfo = new VersionInfo();
            versionInfo.Id = id;
            versionInfo.VersionName = versionName;
            versionInfo.TerminalFileType = terminalFileType;
            versionInfo.CreateTime = createTime;
            return versionInfo;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VersionName
        {
            get
            {
                return _VersionName;
            }
            set
            {
                OnVersionNameChanging(value);
                ReportPropertyChanging("VersionName");
                _VersionName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VersionName");
                OnVersionNameChanged();
            }
        }
        private global::System.String _VersionName;
        partial void OnVersionNameChanging(global::System.String value);
        partial void OnVersionNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TerminalFileType
        {
            get
            {
                return _TerminalFileType;
            }
            set
            {
                OnTerminalFileTypeChanging(value);
                ReportPropertyChanging("TerminalFileType");
                _TerminalFileType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TerminalFileType");
                OnTerminalFileTypeChanged();
            }
        }
        private global::System.String _TerminalFileType;
        partial void OnTerminalFileTypeChanging(global::System.String value);
        partial void OnTerminalFileTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private global::System.DateTime _CreateTime;
        partial void OnCreateTimeChanging(global::System.DateTime value);
        partial void OnCreateTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FileSize
        {
            get
            {
                return _FileSize;
            }
            set
            {
                OnFileSizeChanging(value);
                ReportPropertyChanging("FileSize");
                _FileSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FileSize");
                OnFileSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _FileSize;
        partial void OnFileSizeChanging(Nullable<global::System.Int32> value);
        partial void OnFileSizeChanged();

        #endregion
    
    }

    #endregion
    
}
